[package]
name = "pythnet-sdk"
version = "2.3.2"
description = "Pyth Runtime for Solana"
authors = ["Pyth Data Association"]
repository = "https://github.com/pyth-network/pythnet"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "pythnet_sdk"

[features]
quickcheck = []
solana-program = ["dep:anchor-lang"]
strum = []
test-utils = []
idl-build = ["solana-program", "anchor-lang/idl-build"]

[dependencies]
borsh = { version = "1.6.1", features = ["derive", "unstable__schema"] }
serde = { version = "1.0.144", features = ["derive"] }
anchor-lang  = {version = "1.0.2", optional = true}

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
